[workspace]
members = [
    "common/num-variants",
    "common/short-hex-str",
    "crypto/crypto",
    "crypto/crypto-derive",
    "language/borrow-graph",
    "language/bytecode-verifier",
    "language/move-core/types",
    "language/vm",
    "language/move-vm/runtime",
    "language/move-vm/natives",
    "language/move-vm/types",
    "dvm"
]