[package]
name = "libra-canonical-serialization"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Libra Canonical Serialization (LCS)"
documentation = "https://docs.rs/libra-canonical-serialization"
repository = "https://github.com/libra/lcs"
readme = "README.md"
license = "Apache-2.0"
edition = "2018"

[dependencies]
serde = { version = "1", default-features = false, package = "alt_serde", features = ["derive"] }

[dev-dependencies]
criterion = "0.3.3"
proptest = "0.10.1"
proptest-derive = "0.2.0"

[features]
default = ["std"]

std = [
    "serde/std",
]