[package]
name = "move-vm-types"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Types for Move VM"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
sp-std = { version = "2.0.0", default-features = false }
hashbrown = "0.9"

mirai-annotations = { path = "../../../mirai-annotations", default-features = false }
once_cell = { version = "1.5.2", default-features = false, features = ["unstable", "alloc"] }
sha2 = { version = "0.9.2", default-features = false }
serde = { version = "1", default-features = false, package = "alt_serde", features = ["derive", "alloc"] }

lcs = { path = "../../../lcs", package = "libra-canonical-serialization", default-features = false }
libra-crypto = { path = "../../../crypto/crypto", default-features = false }
move-core-types = { path = "../../move-core/types", default-features = false }
vm = { path = "../../vm", default-features = false }

[features]
default = ["std"]
std = [
	"sha2/std",
	"sp-std/std",
	"vm/std",
	"move-core-types/std",
	"libra-crypto/std",
]
