[package]
name = "move-core-types"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Core types for Move"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
sp-std = { version = "2.0.0", default-features = false } # ok

anyhow = { version = "1.0.34", default-features = false } # ok
hex = { version = "0.4.2", default-features = false } # ok
rand = { version = "0.7.3", default-features = false } # ok
mirai-annotations = "1.10.1" # TODO: fix me
ref-cast = "1.0.3" # ok
serde = { version = "1", default-features = false, package = "alt_serde", features = ["derive"] } # ok
serde_bytes = "0.11.5" # need replacement, depends on std
static_assertions = "1.1.0" # ok
thiserror = "1.0.22" # need replacement, depends on std
once_cell = { version = "1.4.1", default-features = false } # ok

lcs = { path = "../../../lcs", package = "libra-canonical-serialization", default-features = false } # ok
libra-crypto = { path = "../../../crypto/crypto", version = "0.1.0", default-features = false }
libra-crypto-derive = { path = "../../../crypto/crypto-derive", version = "0.1.0" } # ok
short-hex-str = { path = "../../../common/short-hex-str", version = "0.1.0" } # ok

[dev-dependencies]
once_cell = "1.4.1"
proptest-derive = "0.2.0"
regex = "1.4.2"
serde_json = "1.0.59"

[dev-dependencies.proptest]
version = "0.10.1"
features = [
	"alloc", "fork", "timeout", "bit-set",
	# "break-dead-code"
]

[features]
default = ["std", "fiat"]
fiat = ["libra-crypto/fiat"]
std = [
	"anyhow/std",
	"rand/default",
	"sp-std/std",
	"libra-crypto/std",
	"libra-crypto-derive/std",
	"short-hex-str/std",
	# "move-core-types/std",
	# "move-vm-types/std",
	# "vm/std",
]
