[package]
name = "move-vm-natives"
version = "0.1.0"
authors = ["Libra Association <opensource@libra.org>"]
description = "Move VM native functions"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-std = { version = "2.0.0", default-features = false }
once_cell = "1.4.1"
mirai-annotations = "1.10.1"
sha2 = "0.9.2"

libra-crypto = { path = "../../../crypto/crypto", version = "0.1.0" }
move-core-types = { path = "../../move-core/types", version = "0.1.0" }
move-vm-types = { path = "../types", version = "0.1.0" }
vm = { path = "../../vm", version = "0.1.0" }

[features]
default = ["std"]
debug_module = []
std = [
	"sp-std/std",
	"libra-crypto/std",
	"move-core-types/std",
	"move-vm-types/std",
	"vm/std",
]
