name: Tests
on:
  pull_request:
  push:
    branches:
      - master
      - release-*

env:
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: full
  CARGO_INCREMENTAL: 0
  RUSTUP_MAX_RETRIES: 10
  CARGO_NET_RETRY: 10

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.cfg.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        rust:
          - "stable"
        cfg:
          - os: macos-latest
            dove: darwin-x86_64
          - os: ubuntu-latest
            dove: linux-x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Code-style
        run: cargo fmt -- --check

      - name: get Dove
        run: |
          curl -sL --fail \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -o "dove" \
            "https://github.com/pontem-network/move-tools/releases/download/1.2.1/dove-1.2.1-${{ matrix.cfg.dove }}"
          sudo chown runner ./dove && chmod +x ./dove
          mv ./dove ~/.cargo/bin/dove
          dove -V

      - name: Tests
        run: cargo test --all --tests --no-fail-fast -- --test-threads=4 --nocapture

      - name: Clippy
        run: cargo clippy --examples -- -Dwarnings

  build:
    name: Build
    runs-on: ${{ matrix.cfg.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        rust:
          - "nightly-2021-04-24"
        cfg:
          - os: macos-latest
            dove: darwin-x86_64
          - os: ubuntu-latest
            dove: linux-x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: wasm32-unknown-unknown

      - name: get Dove
        run: |
          curl -sL --fail \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -o "dove" \
            "https://github.com/pontem-network/move-tools/releases/download/1.2.1/dove-1.2.1-${{ matrix.cfg.dove }}"
          sudo chown runner ./dove && chmod +x ./dove
          mv ./dove ~/.cargo/bin/dove
          dove -V

      - name: Build WASM -std
        run: |
          cd mvm
          cargo build --package mvm --target wasm32-unknown-unknown --no-default-features

      - name: Build with +std
        run: |
          cd mvm
          cargo build --package mvm --no-default-features --features="std"
